# Generated by Django 5.1.7 on 2025-10-03 11:00

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='About Us', max_length=200)),
                ('subtitle', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Subtitle')),
                ('description', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Description')),
                ('service_1_icon', models.CharField(default='fa fa-comments', help_text='FontAwesome class (e.g., fa fa-comments)', max_length=50)),
                ('service_1_text', models.CharField(default='PA & Audio', max_length=100)),
                ('service_2_icon', models.CharField(default='fa fa-phone', max_length=50)),
                ('service_2_text', models.CharField(default='Intercom & Phone', max_length=100)),
                ('service_3_icon', models.CharField(default='fa fa-lock', max_length=50)),
                ('service_3_text', models.CharField(default='Access Control', max_length=100)),
                ('service_4_icon', models.CharField(default='fa fa-support', max_length=50)),
                ('service_4_text', models.CharField(default='CCTV', max_length=100)),
                ('service_5_icon', models.CharField(default='fa fa-random', max_length=50)),
                ('service_5_text', models.CharField(default='Support', max_length=100)),
                ('service_6_icon', models.CharField(default='fa fa-ambulance', max_length=50)),
                ('service_6_text', models.CharField(default='Maintenance', max_length=100)),
                ('service_7_icon', models.CharField(blank=True, default='fa fa-exclamation-triangle', max_length=50)),
                ('service_7_text', models.CharField(blank=True, max_length=100)),
                ('service_8_icon', models.CharField(default='fa fa-code', max_length=50)),
                ('service_8_text', models.CharField(default='Custom Software', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'About Section',
                'verbose_name_plural': 'About Section',
            },
        ),
        migrations.CreateModel(
            name='ContactSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Get LiT Now!', max_length=200)),
                ('subtitle', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Subtitle')),
                ('phone', models.CharField(default='(954) 445-0712', max_length=50)),
                ('google_maps_embed_url', models.URLField(help_text='Google Maps embed iframe src URL')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Contact Section',
                'verbose_name_plural': 'Contact Section',
            },
        ),
        migrations.CreateModel(
            name='ExamplesSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Examples', max_length=200)),
                ('subtitle', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Subtitle')),
                ('description', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Description')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Examples Section Header',
                'verbose_name_plural': 'Examples Section Header',
            },
        ),
        migrations.CreateModel(
            name='ExampleVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('youtube_url', models.URLField(help_text='Full YouTube URL (will be converted to embed)')),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Example Video',
                'verbose_name_plural': 'Example Videos',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='FooterSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo_image', models.ImageField(upload_to='footer/')),
                ('facebook_url', models.URLField(blank=True)),
                ('twitter_url', models.URLField(blank=True)),
                ('instagram_url', models.URLField(blank=True)),
                ('youtube_url', models.URLField(blank=True)),
                ('copyright_text', models.CharField(default='©2025 LIVE i TECH, Inc.', max_length=200)),
                ('phone', models.CharField(default='(954) 445-0712', max_length=50)),
                ('location', models.CharField(default='Ft. Lauderdale, Fl', max_length=200)),
                ('developer_text', models.CharField(default='Tébar Software', max_length=200)),
                ('developer_url', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Footer Section',
                'verbose_name_plural': 'Footer Section',
            },
        ),
        migrations.CreateModel(
            name='HeroSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo_image', models.ImageField(help_text='Logo image (280x auto)', upload_to='hero/')),
                ('background_image', models.ImageField(help_text='Hero background image', upload_to='hero/')),
                ('is_active', models.BooleanField(default=True, help_text='Display this hero section')),
            ],
            options={
                'verbose_name': 'Hero Section',
                'verbose_name_plural': 'Hero Section',
            },
        ),
        migrations.CreateModel(
            name='PartnerItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('logo', models.ImageField(upload_to='partners/')),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Partner',
                'verbose_name_plural': 'Partners',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='PartnersSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Our Partners', max_length=200)),
                ('subtitle', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Subtitle')),
                ('description', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Description')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Partners Section Header',
                'verbose_name_plural': 'Partners Section Header',
            },
        ),
        migrations.CreateModel(
            name='PortfolioSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Portfolio', max_length=200)),
                ('subtitle', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Subtitle')),
                ('description', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Description')),
                ('image_1', models.ImageField(blank=True, upload_to='portfolio/')),
                ('image_1_alt', models.CharField(default='Portfolio Project 1', max_length=200)),
                ('image_2', models.ImageField(blank=True, upload_to='portfolio/')),
                ('image_2_alt', models.CharField(default='Portfolio Project 2', max_length=200)),
                ('image_3', models.ImageField(blank=True, upload_to='portfolio/')),
                ('image_3_alt', models.CharField(default='Portfolio Project 3', max_length=200)),
                ('image_4', models.ImageField(blank=True, upload_to='portfolio/')),
                ('image_4_alt', models.CharField(default='Portfolio Project 4', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Portfolio Section',
                'verbose_name_plural': 'Portfolio Section',
            },
        ),
        migrations.CreateModel(
            name='ServiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Description')),
                ('image', models.ImageField(upload_to='services/')),
                ('order', models.IntegerField(default=0, help_text='Display order (lower numbers first)')),
                ('anchor_id', models.CharField(blank=True, help_text='HTML anchor ID (e.g., cctv, card)', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Service Item',
                'verbose_name_plural': 'Service Items',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ServicesSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Our Services', max_length=200)),
                ('subtitle', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Subtitle')),
                ('description', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Description')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Services Section Header',
                'verbose_name_plural': 'Services Section Header',
            },
        ),
    ]
